global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'production-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'auth-service:8081'
          - 'order-service:8082'
          - 'payment-service:8083'
        labels: {sandbox: 'production'}

  - job_name: 'shadow-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'shadow-api-gateway:8080'
          - 'shadow-auth-service:8081'
          - 'shadow-order-service:8082'
          - 'shadow-payment-service:8083'
        labels: {sandbox: 'shadow'}

  - job_name: 'otel-collectors'
    static_configs:
      - targets: ['otel-collector:8889']
        labels: {sandbox: 'production'}
      - targets: ['shadow-otel-collector:8889']
        labels: {sandbox: 'shadow'}
